import { createStyleCoreTokens, withAlpha } from "../../core";

export const editorialCollageTokens = createStyleCoreTokens({
  meta: { familyId: "editorial-collage", version: "1.0.0" },
  color: {
    canvas: "#11100D",
    canvasRaised: "#1C1A15",
    surface: "#F1E7D0",
    surfaceElevated: "#FFF7E5",
    surfaceOverlay: "rgba(17, 16, 13, 0.78)",
    textStrong: "#FFF7E5",
    textMuted: "#D8C8A8",
    textSoft: "#A99A7D",
    accent: "#E84A3C",
    accentSoft: withAlpha("#E84A3C", 0.16),
    success: "#4FA86B",
    warning: "#F0B341",
    danger: "#D93B5C",
    rule: "rgba(255, 247, 229, 0.18)",
    shadow: "rgba(0, 0, 0, 0.34)",
    placeholder: "#6D6252",
  },
  spacing: { xs: 8, sm: 12, md: 18, lg: 26, xl: 38, gutter: 22, safeMargin: 66 },
  radius: { sm: 3, md: 5, lg: 7, xl: 8, pill: 999 },
  grid: { columns: 12, gutter: 22, rowGap: 24, outerMargin: 66, maxContentWidth: 948 },
  safeArea: { top: 142, right: 66, bottom: 212, left: 66, captionBottom: 306 },
  motion: {
    policy: "full",
    fastFrames: 8,
    normalFrames: 16,
    slowFrames: 24,
    distanceSm: 10,
    distanceMd: 18,
    distanceLg: 30,
  },
  surface: {
    borderWidth: 1,
    shadowBase: "0 20px 40px rgba(0, 0, 0, 0.22)",
    shadowRaised: "0 26px 58px rgba(0, 0, 0, 0.3)",
    shadowOverlay: "0 30px 70px rgba(0, 0, 0, 0.36)",
    highlight: "inset 0 1px 0 rgba(255, 247, 229, 0.34)",
  },
  media: { cornerRadius: 6, frameInset: 12, placeholderGrid: 32, placeholderLabel: "Asset unavailable" },
  typography: {
    display: { fontFamily: 'Georgia, "Times New Roman", serif', fontSize: 82, lineHeight: 1.03, fontWeight: 800, letterSpacing: 0 },
    headline: { fontFamily: 'Georgia, "Times New Roman", serif', fontSize: 58, lineHeight: 1.07, fontWeight: 800, letterSpacing: 0 },
    title: { fontFamily: '"Be Vietnam Pro", Arial, sans-serif', fontSize: 34, lineHeight: 1.14, fontWeight: 820, letterSpacing: 0 },
    body: { fontFamily: '"Be Vietnam Pro", Arial, sans-serif', fontSize: 25, lineHeight: 1.34, fontWeight: 560, letterSpacing: 0 },
    label: { fontFamily: '"Be Vietnam Pro", Arial, sans-serif', fontSize: 16, lineHeight: 1.16, fontWeight: 820, letterSpacing: 0, textTransform: "uppercase" },
    caption: { fontFamily: '"Be Vietnam Pro", Arial, sans-serif', fontSize: 18, lineHeight: 1.28, fontWeight: 640, letterSpacing: 0 },
    mono: { fontFamily: 'Consolas, "Courier New", monospace', fontSize: 19, lineHeight: 1.28, fontWeight: 650, letterSpacing: 0 },
  },
});
