import { createStyleCoreTokens, withAlpha } from "../../core";

export const timelineDocumentaryTokens = createStyleCoreTokens({
  meta: { familyId: "timeline-documentary", version: "1.0.0" },
  color: {
    canvas: "#151817",
    canvasRaised: "#202321",
    surface: "#E9E2D2",
    surfaceElevated: "#F4EEDF",
    surfaceOverlay: withAlpha("#121514", 0.9),
    textStrong: "#F5F0E5",
    textMuted: "#C8C0AE",
    textSoft: "#938C7E",
    accent: "#D8A93B",
    accentSoft: withAlpha("#D8A93B", 0.18),
    success: "#89A88A",
    warning: "#D8A93B",
    danger: "#C76F5B",
    rule: "rgba(245, 240, 229, 0.18)",
    shadow: "rgba(0, 0, 0, 0.38)",
    placeholder: "#686B65",
  },
  spacing: { xs: 8, sm: 12, md: 20, lg: 28, xl: 40, gutter: 24, safeMargin: 72 },
  radius: { sm: 2, md: 4, lg: 6, xl: 8, pill: 999 },
  grid: { columns: 12, gutter: 24, rowGap: 22, outerMargin: 72, maxContentWidth: 936 },
  safeArea: { top: 132, right: 72, bottom: 196, left: 72, captionBottom: 288 },
  motion: {
    policy: "full",
    fastFrames: 8,
    normalFrames: 16,
    slowFrames: 26,
    distanceSm: 8,
    distanceMd: 16,
    distanceLg: 24,
  },
  surface: {
    borderWidth: 1,
    shadowBase: "0 16px 38px rgba(0, 0, 0, 0.22)",
    shadowRaised: "0 24px 50px rgba(0, 0, 0, 0.3)",
    shadowOverlay: "0 30px 64px rgba(0, 0, 0, 0.38)",
    highlight: "inset 0 1px 0 rgba(255, 255, 255, 0.18)",
  },
  media: { cornerRadius: 3, frameInset: 14, placeholderGrid: 24, placeholderLabel: "Archive image unavailable" },
  typography: {
    display: { fontFamily: 'Georgia, "Times New Roman", serif', fontSize: 82, lineHeight: 1.02, fontWeight: 700, letterSpacing: 0 },
    headline: { fontFamily: 'Georgia, "Times New Roman", serif', fontSize: 49, lineHeight: 1.08, fontWeight: 700, letterSpacing: 0 },
    title: { fontFamily: 'Georgia, "Times New Roman", serif', fontSize: 28, lineHeight: 1.14, fontWeight: 700, letterSpacing: 0 },
    body: { fontFamily: '"Segoe UI", Arial, sans-serif', fontSize: 20, lineHeight: 1.34, fontWeight: 500, letterSpacing: 0 },
    label: { fontFamily: '"Segoe UI", Arial, sans-serif', fontSize: 15, lineHeight: 1.18, fontWeight: 750, letterSpacing: 0, textTransform: "uppercase" },
    caption: { fontFamily: '"Segoe UI", Arial, sans-serif', fontSize: 14, lineHeight: 1.28, fontWeight: 600, letterSpacing: 0 },
    mono: { fontFamily: 'Consolas, "Courier New", monospace', fontSize: 16, lineHeight: 1.2, fontWeight: 600, letterSpacing: 0 },
  },
});
