import { createStyleCoreTokens, withAlpha } from "../../core";

export const productShowcaseTokens = createStyleCoreTokens({
  meta: {
    familyId: "product-showcase",
    version: "1.0.0",
  },
  color: {
    canvas: "#F6F8F6",
    canvasRaised: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceElevated: "#F0F5F2",
    surfaceOverlay: "rgba(255, 255, 255, 0.88)",
    textStrong: "#14211C",
    textMuted: "#52635B",
    textSoft: "#7B8A83",
    accent: "#0F8F7A",
    accentSoft: withAlpha("#0F8F7A", 0.14),
    success: "#2E9F5D",
    warning: "#C58A1B",
    danger: "#C84F55",
    rule: "rgba(20, 33, 28, 0.14)",
    shadow: "rgba(20, 33, 28, 0.18)",
    placeholder: "#D7E1DC",
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 18,
    lg: 24,
    xl: 34,
    gutter: 24,
    safeMargin: 72,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    pill: 999,
  },
  grid: {
    columns: 12,
    gutter: 24,
    rowGap: 24,
    outerMargin: 72,
    maxContentWidth: 936,
  },
  safeArea: {
    top: 150,
    right: 72,
    bottom: 228,
    left: 72,
    captionBottom: 300,
  },
  motion: {
    policy: "full",
    fastFrames: 8,
    normalFrames: 16,
    slowFrames: 24,
    distanceSm: 10,
    distanceMd: 18,
    distanceLg: 30,
  },
  surface: {
    borderWidth: 1,
    shadowBase: "0 18px 42px rgba(20, 33, 28, 0.10)",
    shadowRaised: "0 28px 68px rgba(20, 33, 28, 0.18)",
    shadowOverlay: "0 20px 48px rgba(20, 33, 28, 0.14)",
    highlight: "inset 0 1px 0 rgba(255, 255, 255, 0.72)",
  },
  media: {
    cornerRadius: 10,
    frameInset: 14,
    placeholderGrid: 26,
    placeholderLabel: "Product asset unavailable",
  },
  typography: {
    display: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 78,
      lineHeight: 1.02,
      fontWeight: 860,
      letterSpacing: 0,
    },
    headline: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 50,
      lineHeight: 1.08,
      fontWeight: 820,
      letterSpacing: 0,
    },
    title: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 28,
      lineHeight: 1.16,
      fontWeight: 760,
      letterSpacing: 0,
    },
    body: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 22,
      lineHeight: 1.34,
      fontWeight: 520,
      letterSpacing: 0,
    },
    label: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 15,
      lineHeight: 1.18,
      fontWeight: 780,
      letterSpacing: 0,
      textTransform: "uppercase",
    },
    caption: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 16,
      lineHeight: 1.28,
      fontWeight: 600,
      letterSpacing: 0,
    },
    mono: {
      fontFamily: 'Consolas, "Courier New", monospace',
      fontSize: 16,
      lineHeight: 1.24,
      fontWeight: 600,
      letterSpacing: 0,
    },
  },
});
