import { useEffect, useRef, useState } from 'react'
import { Markdown } from '../lib/markdown'
import { listArtifacts, readArtifact } from '../lib/runsApi'
import type { Artifact, RunEvent, RunState } from '../lib/runsApi'
type Props = { run: RunState | null; events: RunEvent[]; live: boolean; refreshKey: number }
export default function ArtifactRail({ run, events, live, refreshKey }: Props) { const [tab, setTab] = useState<'artifact'|'state'|'events'>('artifact'); const [artifacts, setArtifacts] = useState<Artifact[]>([]); const [selected, setSelected] = useState<{name:string;text:string}|null>(null); const [raw, setRaw] = useState(false); const end = useRef<HTMLDivElement>(null)
  useEffect(() => { if (!run) return; void listArtifacts(run.run_id).then(x => setArtifacts(x.artifacts)).catch(() => undefined) }, [run, refreshKey])
  useEffect(() => { if (live) end.current?.scrollIntoView({ block: 'nearest' }) }, [events, live])
  const choose = (name: string) => void readArtifact(run!.run_id, name).then(setSelected).catch(() => setSelected(null))
  return <aside className="flex min-h-0 min-w-0 flex-col bg-[#181B21] md:w-[42%]"><div className="flex gap-0 border-b border-line px-3 pt-2">{([['artifact','Artifact'],['state','Trạng thái'],['events','Sự kiện']] as const).map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`rounded-t-lg border px-3 py-1.5 text-xs ${tab === id ? 'border-line bg-panel font-semibold text-text' : 'border-transparent text-dim'}`}>{label}</button>)}</div><div className="min-h-0 flex-1 overflow-y-auto p-4 md:p-5">{tab === 'artifact' && <>{artifacts.length === 0 ? <div className="text-xs text-faint">Chưa có artifact</div> : <div className="mb-4 space-y-2">{artifacts.map(a => <button key={a.name} onClick={() => choose(a.name)} className={`block w-full text-left font-mono text-[11px] ${selected?.name === a.name ? 'text-text' : 'text-dim'}`}>▤ <b>{a.name}</b> · {a.chars} ký tự</button>)}</div>}{selected && <div className="text-[13px]"><div className="mb-3 font-mono text-[11px] text-faint">{selected.name}</div><Markdown source={selected.text} /></div>}</>}{tab === 'state' && <StateView run={run} raw={raw} setRaw={setRaw} />}{tab === 'events' && <div className="space-y-2 font-mono text-[10px] text-dim">{events.length === 0 && <div className="text-faint">Chưa có sự kiện</div>}{events.map((event,index) => <div key={`${event.ts}-${index}`} className="border-b border-line pb-1">{event.ts ?? '—'} · {event.type ?? event.event ?? 'event'}{event.node ? ` · ${event.node}` : ''}<div className="truncate text-faint">{shortEvent(event)}</div></div>)}<div ref={end} /></div>}</div></aside> }
function StateView({ run, raw, setRaw }: { run: RunState | null; raw: boolean; setRaw: (x:boolean)=>void }) { const meta = run?.metadata ?? {}; const completed = meta.completed_nodes; return <div className="space-y-3 text-xs text-dim"><div><b className="text-text">Trạng thái</b><div className="font-mono">{run?.status ?? 'chưa chạy'}</div></div><div><b className="text-text">Node hiện tại</b><div className="font-mono">{String(meta.current_node ?? '—')} · index {String(meta.node_index ?? '—')}</div></div><div><b className="text-text">Đã hoàn tất</b><div className="font-mono">{Array.isArray(completed) ? completed.join(', ') || '—' : String(completed ?? '—')}</div></div><div><b className="text-text">Mục tiêu</b><div>{String(meta.objective ?? '—')}</div></div><button onClick={() => setRaw(!raw)} className="text-gemini">{raw ? 'Ẩn raw state' : 'Hiện raw state'}</button>{raw && <pre className="overflow-x-auto whitespace-pre-wrap rounded border border-line bg-panel p-2 font-mono text-[10px] text-dim">{JSON.stringify(run, null, 2)}</pre>}</div> }
function shortEvent(event: RunEvent) { const value = event.text ?? event.message ?? event.reason; return value ? String(value).replace(/\s+/g, ' ').slice(0, 120) : '—' }
