import { ChevronRight, FolderOpen, FolderUp } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api, ApiError } from '../lib/api'
import { Button, EmptyState, Input, Popover } from '../lib/ui'

type Directory = { name: string; path: string }
type DirectoryListing = { path: string | null; parent: string | null; entries: Directory[]; inside_root?: boolean }
type Copy = { choose: string; path: string; up: string; select: string; cancel: string; folderAsContext: string; folderAsScope: string; folderWritable: string; folderWritableWarning: string; noFolders: string }

const labelFor = (path: string) => path.replace(/[\\/]+$/, '').split(/[\\/]/).at(-1) || path
const crumbsFor = (path: string) => {
  const normalized = path.replace(/\\/g, '/'); const parts = normalized.split('/').filter(Boolean); const windowsDrive = /^[A-Za-z]:$/.test(parts[0] ?? ''); let current = windowsDrive ? `${parts.shift()}\\` : normalized.startsWith('/') ? '/' : ''
  return parts.map(part => { current = current === '/' ? `/${part}` : current ? `${current}${windowsDrive ? '\\' : '/'}${part}` : part; return { label: part, path: current } })
}

export default function FolderPicker({ value, onChange, folderAsContext, onFolderAsContextChange, folderAsScope, onFolderAsScopeChange, folderWritable, onFolderWritableChange, copy }: { value: string | null; onChange: (value: string | null, insideRoot?: boolean) => void; folderAsContext: boolean; onFolderAsContextChange: (value: boolean) => void; folderAsScope: boolean; onFolderAsScopeChange: (value: boolean) => void; folderWritable: boolean; onFolderWritableChange: (value: boolean) => void; copy: Copy }) {
  const [listing, setListing] = useState<DirectoryListing>({ path: null, parent: null, entries: [] }); const [path, setPath] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const load = async (target: string | null) => { setLoading(true); setError(''); try { const data = await api<DirectoryListing>(`/api/fs/dirs${target ? `?path=${encodeURIComponent(target)}&show_hidden=false` : '?show_hidden=false'}`); setListing(data); setPath(data.path ?? '') } catch (reason) { setError(reason instanceof ApiError ? reason.message : String(reason)) } finally { setLoading(false) } }
  useEffect(() => { void load(null) }, [])
  const browsePath = () => { if (path.trim()) void load(path.trim()) }
  return <Popover label={<><FolderOpen size={16} strokeWidth={1.75} aria-hidden="true" />{value ? labelFor(value) : copy.choose}</>} aria-label={copy.choose} className="w-[360px] max-h-[520px] overflow-y-auto">{close => <div className="space-y-space-3"><div className="flex items-center gap-space-1"><Button variant="ghost" size="sm" icon={<FolderUp size={16} strokeWidth={1.75} />} aria-label={copy.up} title={copy.up} disabled={!listing.parent || loading} onClick={() => { if (listing.parent) void load(listing.parent) }}>{copy.up}</Button><div className="min-w-0 flex flex-1 items-center overflow-x-auto text-caption text-secondary">{listing.path ? crumbsFor(listing.path).map((crumb, index, crumbs) => <span key={crumb.path} className="inline-flex min-w-0 items-center"><Button variant="ghost" size="sm" className="h-auto px-1 py-0" onClick={() => void load(crumb.path)}>{crumb.label}</Button>{index < crumbs.length - 1 && <ChevronRight size={14} strokeWidth={1.75} aria-hidden="true" />}</span>) : null}</div></div><Input value={path} onChange={event => setPath(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); browsePath() } }} placeholder={copy.path} aria-label={copy.path} /><div className="space-y-1">{listing.entries.length ? listing.entries.map(entry => <Button key={entry.path} variant="ghost" size="sm" className="w-full justify-start" icon={<FolderOpen size={16} strokeWidth={1.75} />} onClick={() => void load(entry.path)}>{entry.name}</Button>) : <EmptyState icon={<FolderOpen size={20} strokeWidth={1.75} />} title={copy.noFolders} className="py-space-4" />}</div><div className="space-y-space-2 border-t border-border-subtle pt-space-3 text-caption text-secondary"><label className="flex items-center gap-space-2"><input type="checkbox" checked={folderAsContext} onChange={event => onFolderAsContextChange(event.target.checked)} />{copy.folderAsContext}</label><label className="flex items-center gap-space-2"><input type="checkbox" checked={folderAsScope} onChange={event => { onFolderAsScopeChange(event.target.checked); if (!event.target.checked) onFolderWritableChange(false) }} />{copy.folderAsScope}</label><label className="flex items-center gap-space-2"><input type="checkbox" checked={folderWritable} onChange={event => onFolderWritableChange(event.target.checked)} disabled={!folderAsScope} />{copy.folderWritable}</label>{folderWritable && <p className="text-warning">{copy.folderWritableWarning}</p>}</div>{error && <p className="text-caption text-error">{error}</p>}<div className="flex justify-end gap-space-2 border-t border-border-subtle pt-space-3"><Button variant="ghost" size="sm" onClick={close}>{copy.cancel}</Button><Button variant="primary" size="sm" disabled={!listing.path || !listing.parent || loading} onClick={() => { if (listing.path) { onChange(listing.path, listing.inside_root !== false); close() } }}>{copy.select}</Button></div></div>}</Popover>
}
