import { useState } from 'react'
import { Markdown } from '../lib/markdown'
import type { IrNode, RunState } from '../lib/runsApi'
import GateCard from './GateCard'

export type NodeView = IrNode & { state: 'pending' | 'running' | 'done' | 'failed'; output: string; reasoning: string; artifact?: boolean; error?: string }
type Props = { nodes: NodeView[]; run?: RunState | null; interrupt?: Record<string, unknown> | null; onGate: (approved: boolean) => void; resuming: boolean }
const providerClass = (agent: IrNode['agent']) => { const p = typeof agent === 'string' ? agent : agent?.provider; return p && ['claude', 'codex', 'nvidia', 'gemini'].includes(p) ? `text-${p} border-${p}` : 'text-faint border-line' }

export default function RunSpine({ nodes, run, interrupt, onGate, resuming }: Props) {
  const objective = String(run?.metadata?.objective ?? '')
  return <div className="min-h-0 flex-1 overflow-y-auto border-r border-line bg-ink p-5 md:p-7"><h1 className="mb-1 text-[17px] font-semibold">Runs workspace</h1><p className="mb-6 text-[13px] text-dim">{objective || 'Chọn workflow và mục tiêu để bắt đầu một phiên chạy.'}</p>{nodes.length === 0 ? <div className="rounded-lg border border-dashed border-line p-5 text-xs text-faint">Spine sẽ hiện sau khi workflow được validate.</div> : <div>{nodes.map((node, index) => <NodeRow key={node.id} node={node} last={index === nodes.length - 1} interrupt={interrupt?.node === node.id ? interrupt : null} onGate={onGate} resuming={resuming} />)}</div>}</div>
}

function NodeRow({ node, last, interrupt, onGate, resuming }: { node: NodeView; last: boolean; interrupt: Record<string, unknown> | null; onGate: (approved: boolean) => void; resuming: boolean }) {
  const [thinkingOpen, setThinkingOpen] = useState(false); const agent = typeof node.agent === 'string' ? node.agent : node.agent?.provider; const model = typeof node.agent === 'string' ? '' : node.agent?.model
  return <article className={`relative pb-6 pl-9 ${node.state === 'pending' ? 'opacity-45' : ''}`}><span className={`absolute left-[2px] top-[3px] z-10 grid h-[18px] w-[18px] place-items-center border-2 bg-ink text-[9px] ${node.gate ? 'rotate-45 rounded-[3px] border-gate text-gate' : `rounded-full ${node.state === 'done' ? 'border-ok text-ok' : node.state === 'failed' ? 'border-err text-err' : node.state === 'running' ? 'border-claude text-claude node-pulse' : 'border-faint text-faint'}`}`}>{node.state === 'done' ? <span className="-rotate-45">✓</span> : node.state === 'failed' ? <span className="-rotate-45">!</span> : ''}</span>{!last && <span className="absolute left-[10px] top-[22px] bottom-[-2px] w-[2px] bg-line" />}<div className="mb-1.5 flex flex-wrap items-baseline gap-2"><span className="text-sm font-semibold">{node.id}</span>{node.artifact && <span className="font-mono text-[10px] text-faint">¤</span>}{agent && <span className={`rounded-full border px-2 py-px font-mono text-[10px] ${providerClass(node.agent)}`}>{agent}{model ? ` · ${model}` : ''}</span>}<span className="font-mono text-[10px] text-faint">{node.state}</span></div><div className={`rounded-[10px] border border-line bg-panel p-3 text-[13px] ${node.state === 'running' ? 'border-l-2 border-l-claude' : ''}`}>{node.output ? (node.state === 'done' ? <Markdown source={node.output} /> : <div className="whitespace-pre-wrap font-mono text-xs text-text">{node.output}{node.state === 'running' && <i className="ml-1 inline-block h-3 w-1.5 animate-pulse bg-claude" />}</div>) : <span className="text-faint">Đang chờ node này…</span>}{node.error && <div className="mt-2 text-xs text-err">{node.error}</div>}{node.reasoning && <><button onClick={() => setThinkingOpen(!thinkingOpen)} className="mt-2 text-[10px] text-faint">{thinkingOpen ? 'Ẩn suy nghĩ' : 'Hiện suy nghĩ'}</button>{thinkingOpen && <div className="mt-1 whitespace-pre-wrap border-l border-line pl-2 font-mono text-[10px] text-faint">{node.reasoning}</div>}</>}{interrupt && <GateCard interrupt={interrupt} onChoice={onGate} resuming={resuming} />}</div></article>
}
