import { useEffect, useState, type KeyboardEvent } from 'react'
import { NavLink, useLocation, useNavigate } from 'react-router-dom'
import { ApiError, api } from '../lib/api'
import { Input, Popover, Status } from '../lib/ui'

const titles: Record<string, string> = { overview: 'Overview', chat: 'Chat đa cửa sổ', sessions: 'Phiên đã lưu', workflows: 'Workflows', artifacts: 'Artifacts', runs: 'Runs', agents: 'Agents', skills: 'Skills', hooks: 'Hooks', files: 'Files', approvals: 'Chờ duyệt', usage: 'Usage & quota', settings: 'Cài đặt' }
const tabs = [['Chat', '/chat'], ['Workflows', '/workflows'], ['Artifacts', '/artifacts'], ['Agents', '/agents'], ['Skills', '/skills'], ['Hooks', '/hooks'], ['Files', '/files'], ['Settings', '/settings']] as const
type SearchResult = { type: 'workflow' | 'agent' | 'skill' | 'artifact'; id: string; title: string; context: string; href: string }
const typeLabels: Record<SearchResult['type'], string> = { workflow: 'Workflow', agent: 'Agent', skill: 'Skill', artifact: 'Artifact' }

export default function Topbar() {
  const [providers, setProviders] = useState<{ id: string; available: boolean; detail?: string }[] | null>(null); const [providersError, setProvidersError] = useState('')
  const [query, setQuery] = useState(''); const [results, setResults] = useState<SearchResult[]>([]); const [searchError, setSearchError] = useState(''); const [active, setActive] = useState(0)
  const navigate = useNavigate()
  useEffect(() => { void api<{ id: string; available: boolean; detail?: string }[]>('/api/providers').then(setProviders).catch(error => setProvidersError(error instanceof ApiError ? error.message : 'Không thể tải provider')) }, [])
  useEffect(() => { const value = query.trim(); setActive(0); if (value.length < 2) { setResults([]); setSearchError(''); return } let current = true; void api<SearchResult[]>(`/api/search?q=${encodeURIComponent(value)}`).then(data => { if (current) { setResults(data); setSearchError('') } }).catch(error => { if (current) { setResults([]); setSearchError(error instanceof ApiError ? error.message : 'Không thể tìm kiếm') } }); return () => { current = false } }, [query])
  const page = useLocation().pathname.split('/')[1] || 'runs'; const title = titles[page] ?? 'Runs'
  const choose = (result: SearchResult, close: () => void) => { navigate(result.href); close() }
  const searchKeyDown = (event: KeyboardEvent<HTMLInputElement>, close: () => void) => { if (event.key === 'ArrowDown' && results.length) { event.preventDefault(); setActive(current => Math.min(current + 1, results.length - 1)) } else if (event.key === 'ArrowUp' && results.length) { event.preventDefault(); setActive(current => Math.max(current - 1, 0)) } else if (event.key === 'Enter' && results[active]) { event.preventDefault(); choose(results[active], close) } }
  return <header className="flex h-toolbar shrink-0 items-center gap-space-4 overflow-hidden border-b border-border-subtle bg-sidebar px-[18px]">
    <span className="shrink-0 text-label text-secondary"><b className="font-semibold text-primary">Harness Hub</b> / {title}</span>
    <nav className="flex min-w-0 flex-1 items-stretch justify-center gap-space-1 self-stretch overflow-hidden" aria-label="Điều hướng chính">{tabs.map(([label, to]) => <NavLink key={to} to={to} className={({ isActive }) => `flex shrink-0 items-center border-b-2 px-space-2 text-caption no-underline ${isActive ? 'border-accent text-primary' : 'border-transparent text-secondary hover:text-primary'}`}>{label}</NavLink>)}</nav>
    <div className="flex shrink-0 items-center gap-space-1"><Popover aria-label="Tìm kiếm toàn cục" label="⌕" className="w-[280px]">{close => <div><Input aria-label="Tìm kiếm toàn cục" placeholder="Tìm kiếm…" value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => searchKeyDown(event, close)} aria-activedescendant={results[active] ? `global-search-${active}` : undefined} />{searchError ? <p className="mt-space-2 text-caption text-error">{searchError}</p> : query.trim().length < 2 ? <p className="mt-space-2 text-caption text-muted">Nhập ít nhất 2 ký tự.</p> : results.length ? <div className="mt-space-2 max-h-72 overflow-auto" role="listbox" aria-label="Kết quả tìm kiếm">{results.map((result, index) => <button key={`${result.type}-${result.id}`} id={`global-search-${index}`} type="button" role="option" aria-selected={index === active} onMouseEnter={() => setActive(index)} onClick={() => choose(result, close)} className={`block w-full rounded-md px-space-2 py-space-2 text-left hover:bg-hover ${index === active ? 'bg-hover' : ''}`}><div className="flex items-center gap-space-2 text-caption"><span className="text-muted">{typeLabels[result.type]}</span><span className="truncate text-primary">{result.title}</span></div><div className="truncate text-caption text-secondary">{result.context}</div></button>)}</div> : <p className="mt-space-2 text-caption text-muted">Không có kết quả phù hợp.</p>}</div>}</Popover><Popover aria-label="Trạng thái provider" align="end" label="●"><div className="space-y-space-2">{providersError ? <p className="text-caption text-error">{providersError}</p> : <><Status kind="ready" label={providers ? `${providers.filter(provider => provider.available).length} provider online` : '—'} />{providers?.map(provider => <div key={provider.id} className="text-caption text-secondary">{provider.id} · {provider.available ? 'available' : provider.detail || 'unavailable'}</div>)}</>}</div></Popover><span aria-label="Người dùng" className="grid h-8 w-8 place-items-center rounded-full bg-elevated text-caption font-semibold text-primary">U</span></div>
  </header>
}
