import type { CSSProperties } from "react";
import { AbsoluteFill, useCurrentFrame } from "remotion";
import { BoxFrame, Surface, buildEntranceStyle, fitTypographyToBox, resolveVerticalLayout } from "../../core";
import { newsRundownFixtures } from "../../../../pipeline/fixtures/styles/news-rundown";
import { newsRundownTokens } from "./tokens";
import type { NewsItem, NewsRundownFixture, NewsRundownVariantId } from "./types";

const copy = (style: CSSProperties): CSSProperties => ({ overflowWrap: "anywhere", ...style });
const labelStyle: CSSProperties = { color: newsRundownTokens.color.accent, fontFamily: newsRundownTokens.typography.label.fontFamily, fontSize: 14, fontWeight: 760 };
const Item = ({ item, index, fixture, numbered = false, timeline = false }: { item: NewsItem; index: number; fixture: NewsRundownFixture; numbered?: boolean; timeline?: boolean }) => {
  const frame = useCurrentFrame();
  return <div style={{ ...buildEntranceStyle({ frame, durationInFrames: 14, delayFrames: index * 3 + 5, preset: "fade-up", distance: 8, policy: fixture.motionPolicy }), display: "grid", gridTemplateColumns: timeline ? "98px 18px minmax(0, 1fr)" : numbered ? "56px minmax(0, 1fr)" : "minmax(0, 1fr)", gap: 14, padding: "16px 0", borderTop: `1px solid ${newsRundownTokens.color.rule}` }}>
    {timeline ? <><div style={{ ...labelStyle, color: newsRundownTokens.color.warning, textAlign: "right" }}>{item.timestamp}</div><div style={{ position: "relative" }}><span style={{ position: "absolute", top: 4, left: 3, width: 12, height: 12, borderRadius: 99, background: index === 0 ? newsRundownTokens.color.danger : newsRundownTokens.color.accent }} /></div></> : numbered ? <div style={{ color: newsRundownTokens.color.warning, fontFamily: newsRundownTokens.typography.display.fontFamily, fontSize: 36, fontWeight: 820, lineHeight: 1 }}>{String(index + 1).padStart(2, "0")}</div> : null}
    <div><div style={labelStyle}>{item.label}</div><div style={copy({ marginTop: 5, color: newsRundownTokens.color.textStrong, fontFamily: newsRundownTokens.typography.title.fontFamily, fontSize: 25, lineHeight: 1.13, fontWeight: 760 })}>{item.headline}</div><div style={copy({ marginTop: 7, color: newsRundownTokens.color.textMuted, fontFamily: newsRundownTokens.typography.caption.fontFamily, fontSize: 16, lineHeight: 1.22, fontWeight: 580 })}>{item.detail}</div></div>
  </div>;
};

const Header = ({ fixture }: { fixture: NewsRundownFixture }) => {
  const fit = fitTypographyToBox({ tokens: newsRundownTokens, role: "headline", text: fixture.headline, width: 936, height: 160, maxLines: 3, density: fixture.density, minScale: 0.68 });
  return <><div style={{ display: "flex", justifyContent: "space-between", color: newsRundownTokens.color.accent, fontFamily: newsRundownTokens.typography.label.fontFamily, fontSize: 15, fontWeight: 760 }}><span>{fixture.section}</span><span>DRAFT / 9:16</span></div><div style={copy({ marginTop: 15, color: newsRundownTokens.color.textStrong, fontFamily: fit.style.fontFamily, fontSize: fit.style.fontSize, lineHeight: fit.style.lineHeight, fontWeight: fit.style.fontWeight })}>{fixture.headline}</div><div style={{ marginTop: 12, display: "flex", justifyContent: "space-between", color: newsRundownTokens.color.textMuted, fontFamily: newsRundownTokens.typography.caption.fontFamily, fontSize: 16, fontWeight: 600 }}><span>{fixture.sourceLabel}</span><span>{fixture.timestamp}</span></div></>;
};

export const NewsRundownScene = ({ sceneKey, fixture: override }: { sceneKey?: NewsRundownVariantId; fixture?: NewsRundownFixture }) => {
  const frame = useCurrentFrame();
  const fixture = override ?? newsRundownFixtures[sceneKey ?? "breaking-update"];
  const layout = resolveVerticalLayout({ platform: "tiktok", contentInset: { top: 12, bottom: 12 }, maxContentWidth: 936 });
  const header = { x: layout.content.x, y: layout.content.y, width: layout.content.width, height: 318 };
  const main = { x: layout.content.x, y: header.y + header.height + 24, width: layout.content.width, height: 650 };
  const caption = { x: layout.content.x, y: main.y + main.height + 24, width: layout.content.width, height: 180 };
  const body = fixture.key === "breaking-update" ? <Surface tokens={newsRundownTokens} elevation="raised" style={{ height: "100%", padding: 28, borderRadius: 8, borderTop: `8px solid ${newsRundownTokens.color.danger}` }}><div style={{ color: newsRundownTokens.color.danger, fontFamily: newsRundownTokens.typography.label.fontFamily, fontSize: 16, fontWeight: 800 }}>Breaking brief</div><div style={copy({ marginTop: 22, color: newsRundownTokens.color.textStrong, fontFamily: newsRundownTokens.typography.display.fontFamily, fontSize: 62, lineHeight: 1.02, fontWeight: 850 })}>{fixture.summary}</div><div style={{ marginTop: 28 }}><Item item={fixture.items[0]} index={0} fixture={fixture} /></div></Surface>
    : fixture.key === "headline-stack" ? <Surface tokens={newsRundownTokens} elevation="raised" style={{ height: "100%", padding: "8px 24px", borderRadius: 8 }}>{fixture.items.map((item, index) => <Item key={item.label} item={item} index={index} fixture={fixture} numbered />)}</Surface>
    : fixture.key === "top-stories" ? <Surface tokens={newsRundownTokens} elevation="raised" style={{ height: "100%", padding: "10px 24px", borderRadius: 8, background: "#13202A" }}><div style={{ ...labelStyle, color: newsRundownTokens.color.warning, padding: "10px 0" }}>Developing timeline</div>{fixture.items.map((item, index) => <Item key={item.label} item={item} index={index} fixture={fixture} timeline />)}</Surface>
    : fixture.key === "bulletin-grid" ? <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, height: "100%" }}>{fixture.items.map((item, index) => <Surface key={item.label} tokens={newsRundownTokens} elevation="raised" style={{ ...buildEntranceStyle({ frame, durationInFrames: 14, delayFrames: index * 3 + 5, preset: "fade-up", distance: 8, policy: fixture.motionPolicy }), padding: 20, borderRadius: 8 }}><div style={labelStyle}>{item.label}</div><div style={copy({ marginTop: 14, color: newsRundownTokens.color.textStrong, fontFamily: newsRundownTokens.typography.title.fontFamily, fontSize: 26, lineHeight: 1.12, fontWeight: 760 })}>{item.headline}</div><div style={copy({ marginTop: 10, color: newsRundownTokens.color.textMuted, fontFamily: newsRundownTokens.typography.caption.fontFamily, fontSize: 16, lineHeight: 1.22, fontWeight: 580 })}>{item.detail}</div></Surface>)}</div>
    : <Surface tokens={newsRundownTokens} elevation="raised" style={{ height: "100%", padding: 28, borderRadius: 8 }}><div style={labelStyle}>Signal watch</div><div style={{ display: "flex", alignItems: "end", gap: 18, marginTop: 14 }}><div style={{ color: newsRundownTokens.color.textStrong, fontFamily: newsRundownTokens.typography.display.fontFamily, fontSize: 94, lineHeight: 0.94, fontWeight: 850 }}>{fixture.metric?.value}</div><div style={{ color: newsRundownTokens.color.success, fontFamily: newsRundownTokens.typography.title.fontFamily, fontSize: 26, fontWeight: 760 }}>{fixture.metric?.change}</div></div><div style={copy({ marginTop: 12, color: newsRundownTokens.color.textMuted, fontFamily: newsRundownTokens.typography.body.fontFamily, fontSize: 20, lineHeight: 1.22, fontWeight: 600 })}>{fixture.metric?.label}</div><div style={{ marginTop: 24 }}>{fixture.items.map((item, index) => <Item key={item.label} item={item} index={index} fixture={fixture} />)}</div></Surface>;
  return <AbsoluteFill style={{ background: newsRundownTokens.color.canvas, color: newsRundownTokens.color.textStrong }}><div style={{ position: "absolute", inset: 0, opacity: 0.36, backgroundImage: `linear-gradient(${newsRundownTokens.color.rule} 1px, transparent 1px)`, backgroundSize: "100% 64px" }} /><BoxFrame box={header}><div style={buildEntranceStyle({ frame, durationInFrames: 16, preset: "fade-up", distance: 14, policy: fixture.motionPolicy })}><Header fixture={fixture} /></div></BoxFrame><BoxFrame box={main}>{body}</BoxFrame><BoxFrame box={caption}><Surface tokens={newsRundownTokens} style={{ ...buildEntranceStyle({ frame, durationInFrames: 14, delayFrames: 8, preset: "fade-up", distance: 8, policy: fixture.motionPolicy }), height: "100%", padding: 20, borderRadius: 8, display: "grid", gridTemplateColumns: "140px minmax(0, 1fr)", gap: 18 }}><div style={{ ...labelStyle, color: newsRundownTokens.color.warning }}>Why it matters</div><div style={copy({ color: newsRundownTokens.color.textStrong, fontFamily: newsRundownTokens.typography.body.fontFamily, fontSize: 20, lineHeight: 1.26, fontWeight: 620 })}>{fixture.caption}</div></Surface></BoxFrame></AbsoluteFill>;
};
