const templateFor = {
  terminal: "code-panel",
  code: "code-panel",
  editorial: "animated-list",
  infographic: "animated-list",
  dashboard: "progress-steps",
  data_visualization: "progress-steps",
  product_demo: "split-screen",
  cinematic_typography: "cinematic-title-intro",
};

const contentFor = (scene) => {
  const texts = scene.blocks.map((block) => block.text).filter(Boolean);
  const base = {
    kicker: scene.visualFamily.toUpperCase().replaceAll("_", " "),
    title: scene.title ?? texts[0] ?? "Visual scene",
    subtitle: texts[1] ?? "",
    footer: scene.preset,
  };
  if (scene.visualFamily === "terminal" || scene.visualFamily === "code") {
    const lines = texts.flatMap((text) => text.split(/\r?\n/))
      .map((line) => line.trim())
      .filter(Boolean);
    if (lines[0] === scene.title) lines.shift();
    return {
      ...base,
      codeTitle: scene.preset,
      lines: lines.length ? lines : ["No output"],
      highlights: lines.map((_, i) => i),
    };
  }
  if (
    scene.visualFamily === "dashboard" ||
    scene.visualFamily === "data_visualization"
  ) {
    return {
      ...base,
      steps: texts.map((text, index) => ({
        number: String(index + 1).padStart(2, "0"),
        title: text,
      })),
    };
  }
  return {
    ...base,
    items: texts.map((text, index) => ({
      number: String(index + 1).padStart(2, "0"),
      title: text,
    })),
  };
};

export const compileVideoMap = (mapped, config) => {
  const scenes = mapped.scenes.map((scene) => {
    const text = scene.blocks
      .map((block) => block.text)
      .filter(Boolean)
      .join(" ");
    return {
      id: scene.sceneId,
      intent:
        scene.visualFamily === "terminal" || scene.visualFamily === "code"
          ? "code_explanation"
          : "process",
      templateId: templateFor[scene.visualFamily] ?? "animated-list",
      templateRole: "scene",
      durationSec: scene.durationInFrames / config.fps,
      headline: scene.title ?? "Visual scene",
      subtitle: {
        text: text || scene.title || "Visual scene",
        segments: [text || scene.title || "Visual scene"],
      },
      content: contentFor(scene),
      style: {
        density:
          scene.blocks.length > 6
            ? "high"
            : scene.blocks.length > 3
              ? "medium"
              : "low",
        safeArea: "tiktok",
      },
      motion:
        scene.visualFamily === "terminal"
          ? ["terminal_reveal", "line_typewriter"]
          : ["staggered_list", "title_reveal"],
      backgroundEffect:
        scene.visualFamily === "terminal" ? "matrix-rain" : "noise-grain",
      transitionIn: "cross-dissolve",
      transitionOut: "cross-dissolve",
      subtitleMode:
        scene.visualFamily === "terminal" || scene.visualFamily === "code"
          ? "none"
          : "bar",
      reason: `Compiled from ${scene.visualFamily}/${scene.preset} with provenance-backed blocks${scene.knowledgeEvidence?.length ? ` and ${scene.knowledgeEvidence.length} approved RAG evidence item(s)` : ""}.`,
    };
  });
  const durationSec = scenes.reduce((sum, scene) => sum + scene.durationSec, 0);
  return {
    video: {
      title: config.projectId,
      subtitle: "Generated by Lucida visual input pipeline",
      format: "vertical_9_16",
      width: 1080,
      height: 1920,
      fps: config.fps,
      durationSec,
      style: "lucida_visual_pipeline",
      language: "en",
      sourceBlocks: mapped.scenes.flatMap((scene) =>
        scene.blocks.flatMap((block) => block.sourceEventIds),
      ),
    },
    theme: {
      name: config.themeId,
      accent: "#D2B47A",
      accentSoft: "#F4E2BD",
      background: "#0B0C0E",
      foreground: "#F4F0E8",
      muted: "#A7A39B",
    },
    assets: [],
    scenes,
  };
};
