import { createStyleCoreTokens } from "../../core";

export const technicalEditorialTokens = createStyleCoreTokens({
  meta: {
    familyId: "technical-editorial",
    version: "1.0.0",
  },
  color: {
    canvas: "#0B1017",
    canvasRaised: "#121926",
    surface: "#101826",
    surfaceElevated: "#172131",
    surfaceOverlay: "rgba(7, 10, 16, 0.82)",
    textStrong: "#F4F7FB",
    textMuted: "#BCC7D6",
    textSoft: "#8191A7",
    accent: "#7AA2FF",
    accentSoft: "rgba(122, 162, 255, 0.14)",
    success: "#57C084",
    warning: "#F2BC65",
    danger: "#F17E8E",
    rule: "rgba(244, 247, 251, 0.13)",
    shadow: "rgba(0, 0, 0, 0.34)",
    placeholder: "#4E5C6E",
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 20,
    lg: 28,
    xl: 36,
    gutter: 24,
    safeMargin: 72,
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
    pill: 999,
  },
  grid: {
    columns: 12,
    gutter: 24,
    rowGap: 24,
    outerMargin: 72,
    maxContentWidth: 936,
  },
  motion: {
    policy: "full",
    fastFrames: 8,
    normalFrames: 16,
    slowFrames: 24,
    distanceSm: 10,
    distanceMd: 18,
    distanceLg: 28,
  },
  surface: {
    borderWidth: 1,
    shadowBase: "0 18px 42px rgba(0, 0, 0, 0.2)",
    shadowRaised: "0 24px 52px rgba(0, 0, 0, 0.24)",
    shadowOverlay: "0 30px 60px rgba(0, 0, 0, 0.3)",
    highlight: "inset 0 1px 0 rgba(255, 255, 255, 0.06)",
  },
  media: {
    cornerRadius: 16,
    frameInset: 16,
    placeholderGrid: 24,
    placeholderLabel: "Reference pending",
  },
  typography: {
    display: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 92,
      lineHeight: 1.02,
      fontWeight: 900,
      letterSpacing: 0,
    },
    headline: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 58,
      lineHeight: 1.08,
      fontWeight: 820,
      letterSpacing: 0,
    },
    title: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 34,
      lineHeight: 1.14,
      fontWeight: 760,
      letterSpacing: 0,
    },
    body: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 24,
      lineHeight: 1.34,
      fontWeight: 520,
      letterSpacing: 0,
    },
    label: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 18,
      lineHeight: 1.16,
      fontWeight: 760,
      letterSpacing: 0,
      textTransform: "uppercase",
    },
    caption: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 17,
      lineHeight: 1.24,
      fontWeight: 620,
      letterSpacing: 0,
    },
    mono: {
      fontFamily: 'Consolas, "Courier New", monospace',
      fontSize: 19,
      lineHeight: 1.32,
      fontWeight: 600,
      letterSpacing: 0,
    },
  },
});
