import { createStyleCoreTokens, withAlpha } from "../../core";

export const dashboardDataTokens = createStyleCoreTokens({
  meta: {
    familyId: "dashboard-data",
    version: "1.0.0",
  },
  color: {
    canvas: "#091018",
    canvasRaised: "#101923",
    surface: "#111C27",
    surfaceElevated: "#162331",
    surfaceOverlay: "rgba(9, 16, 24, 0.86)",
    textStrong: "#EEF4FB",
    textMuted: "#B5C3D3",
    textSoft: "#7890A8",
    accent: "#61A5FA",
    accentSoft: withAlpha("#61A5FA", 0.16),
    success: "#49C27D",
    warning: "#F4B560",
    danger: "#F1737A",
    rule: "rgba(238, 244, 251, 0.12)",
    shadow: "rgba(0, 0, 0, 0.34)",
    placeholder: "#5B6C80",
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 18,
    lg: 24,
    xl: 36,
    gutter: 24,
    safeMargin: 72,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    pill: 999,
  },
  grid: {
    columns: 12,
    gutter: 24,
    rowGap: 24,
    outerMargin: 72,
    maxContentWidth: 936,
  },
  safeArea: {
    top: 164,
    right: 72,
    bottom: 212,
    left: 72,
    captionBottom: 302,
  },
  motion: {
    policy: "full",
    fastFrames: 8,
    normalFrames: 16,
    slowFrames: 24,
    distanceSm: 10,
    distanceMd: 18,
    distanceLg: 28,
  },
  surface: {
    borderWidth: 1,
    shadowBase: "0 18px 44px rgba(0, 0, 0, 0.18)",
    shadowRaised: "0 24px 52px rgba(0, 0, 0, 0.24)",
    shadowOverlay: "0 30px 60px rgba(0, 0, 0, 0.28)",
    highlight: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  media: {
    cornerRadius: 10,
    frameInset: 16,
    placeholderGrid: 24,
    placeholderLabel: "Dashboard placeholder",
  },
  typography: {
    display: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 86,
      lineHeight: 1.02,
      fontWeight: 900,
      letterSpacing: 0,
    },
    headline: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 52,
      lineHeight: 1.06,
      fontWeight: 840,
      letterSpacing: 0,
    },
    title: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 28,
      lineHeight: 1.16,
      fontWeight: 760,
      letterSpacing: 0,
    },
    body: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 22,
      lineHeight: 1.34,
      fontWeight: 520,
      letterSpacing: 0,
    },
    label: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 16,
      lineHeight: 1.18,
      fontWeight: 760,
      letterSpacing: 0,
      textTransform: "uppercase",
    },
    caption: {
      fontFamily: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
      fontSize: 15,
      lineHeight: 1.28,
      fontWeight: 620,
      letterSpacing: 0,
    },
    mono: {
      fontFamily: 'Consolas, "Courier New", monospace',
      fontSize: 17,
      lineHeight: 1.24,
      fontWeight: 600,
      letterSpacing: 0,
    },
  },
});
