import { AbsoluteFill, interpolate, useCurrentFrame } from "remotion";
import { interfaceWalkthroughFixtures } from "../../../../pipeline/fixtures/styles/interface-walkthrough";
import { interfaceWalkthroughTokens as t } from "./tokens";
import type { InterfaceWalkthroughFixture, InterfaceWalkthroughVariantId } from "./types";

const stateColor = (state: InterfaceWalkthroughFixture["items"][number]["state"]) =>
  state === "complete" ? t.success : state === "blocked" ? t.danger : state === "active" ? t.warning : t.muted;

const Panel = ({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) => (
  <div style={{ background: t.panel, border: `1px solid ${t.rule}`, borderRadius: 8, ...style }}>{children}</div>
);

const ScreenContent = ({ fixture }: { fixture: InterfaceWalkthroughFixture }) => {
  if (fixture.layout === "mobile") return <div style={{ display: "flex", justifyContent: "center", height: "100%" }}><Panel style={{ width: 390, padding: 18, background: "#0C1119", borderRadius: 34 }}><div style={{ margin: "0 auto 24px", width: 110, height: 7, borderRadius: 9, background: t.panelRaised }} /><div style={{ color: t.text, fontWeight: 760, fontSize: 24 }}>Today</div><div style={{ marginTop: 20, display: "grid", gap: 12 }}>{fixture.items.map((item) => <div key={item.label} style={{ padding: 14, background: t.panel, border: `1px solid ${item.state === "active" ? t.accent : t.rule}`, borderRadius: 8 }}><div style={{ color: t.text, fontWeight: 720 }}>{item.label}</div><div style={{ marginTop: 5, color: t.muted, fontSize: 15 }}>{item.detail}</div></div>)}</div></Panel></div>;
  if (fixture.layout === "workflow") return <div style={{ display: "grid", gap: 16 }}>{fixture.items.map((item, index) => <div key={item.label} style={{ display: "grid", gridTemplateColumns: "42px minmax(0, 1fr)", gap: 14, alignItems: "center", padding: 16, border: `1px solid ${item.state === "active" ? t.accent : t.rule}`, borderRadius: 8, background: item.state === "active" ? "rgba(85,183,246,0.10)" : t.panel }}><div style={{ width: 32, height: 32, borderRadius: 16, display: "grid", placeItems: "center", background: stateColor(item.state), color: t.canvas, fontWeight: 800 }}>{index + 1}</div><div><div style={{ color: t.text, fontWeight: 740 }}>{item.label}</div><div style={{ marginTop: 4, color: t.muted, fontSize: 16 }}>{item.detail}</div></div></div>)}</div>;
  if (fixture.layout === "table") return <Panel style={{ overflow: "hidden" }}><div style={{ display: "grid", gridTemplateColumns: "1.3fr 1fr .7fr", gap: 12, padding: "14px 16px", color: t.muted, fontFamily: t.mono, fontSize: 13, borderBottom: `1px solid ${t.rule}` }}><span>RECORD</span><span>OWNER</span><span>STATE</span></div>{fixture.items.map((item) => <div key={item.label} style={{ display: "grid", gridTemplateColumns: "1.3fr 1fr .7fr", gap: 12, padding: "16px", borderBottom: `1px solid ${t.rule}`, background: item.state === "active" ? "rgba(85,183,246,0.10)" : "transparent" }}><span style={{ color: t.text, fontWeight: 700 }}>{item.label}</span><span style={{ color: t.muted }}>{item.detail}</span><span style={{ color: stateColor(item.state), fontWeight: 700 }}>{item.state ?? "ready"}</span></div>)}</Panel>;
  if (fixture.layout === "settings") return <div style={{ display: "grid", gap: 12 }}>{fixture.items.map((item) => <Panel key={item.label} style={{ padding: 16, borderColor: item.state === "active" ? t.accent : t.rule }}><div style={{ display: "flex", justifyContent: "space-between", gap: 16 }}><div><div style={{ color: t.text, fontWeight: 740 }}>{item.label}</div><div style={{ marginTop: 5, color: t.muted, fontSize: 16 }}>{item.detail}</div></div><div style={{ width: 44, height: 24, padding: 3, borderRadius: 14, background: item.state === "active" ? t.accent : t.panelRaised }}><div style={{ width: 18, height: 18, borderRadius: 10, background: t.text, marginLeft: item.state === "active" ? 20 : 0 }} /></div></div></Panel>)}</div>;
  return <div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 14 }}>{fixture.items.map((item) => <Panel key={item.label} style={{ minHeight: 142, padding: 16, borderColor: item.state === "active" ? t.accent : t.rule }}><div style={{ color: t.muted, fontSize: 14, fontWeight: 720 }}>{item.label}</div><div style={{ marginTop: 16, color: t.text, fontSize: 30, fontWeight: 820 }}>{item.detail}</div><div style={{ marginTop: 12, color: stateColor(item.state), fontSize: 14 }}>{item.state ?? "ready"}</div></Panel>)}</div>;
};

export const InterfaceWalkthroughScene = ({ sceneKey, fixture: override }: { sceneKey?: InterfaceWalkthroughVariantId; fixture?: InterfaceWalkthroughFixture }) => {
  const frame = useCurrentFrame();
  const fixture = override ?? interfaceWalkthroughFixtures[sceneKey ?? "annotated-screen"];
  const opacity = fixture.motionPolicy === "static" ? 1 : interpolate(frame, [0, 12], [0, 1], { extrapolateRight: "clamp" });
  return <AbsoluteFill style={{ background: t.canvas, color: t.text, fontFamily: t.font }}><div style={{ position: "absolute", inset: 0, opacity: .38, backgroundImage: `linear-gradient(${t.rule} 1px, transparent 1px)`, backgroundSize: "100% 46px" }} /><div style={{ position: "absolute", inset: "72px", opacity }}><header><div style={{ display: "flex", justifyContent: "space-between", color: t.accent, fontSize: 15, fontWeight: 780 }}><span>{fixture.eyebrow}</span><span>DRAFT / 9:16</span></div><h1 style={{ margin: "16px 0 0", maxWidth: 880, fontSize: 48, lineHeight: 1.1, letterSpacing: 0 }}>{fixture.title}</h1><p style={{ margin: "14px 0 26px", maxWidth: 870, color: t.muted, fontSize: 19, lineHeight: 1.3 }}>{fixture.summary}</p></header><Panel style={{ height: 920, display: "grid", gridTemplateColumns: "178px minmax(0, 1fr)", overflow: "hidden" }}><aside style={{ padding: 16, borderRight: `1px solid ${t.rule}` }}><div style={{ color: t.text, fontWeight: 820, marginBottom: 26 }}>{fixture.product}</div>{fixture.navigation.map((item) => <div key={item} style={{ padding: "11px 10px", color: item === fixture.navigation[0] ? t.text : t.muted, background: item === fixture.navigation[0] ? t.panelRaised : "transparent", borderRadius: 6, marginBottom: 5 }}>{item}</div>)}</aside><main style={{ minWidth: 0, padding: 20 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", paddingBottom: 18, borderBottom: `1px solid ${t.rule}` }}><span style={{ color: t.text, fontWeight: 760 }}>{fixture.label}</span><span style={{ padding: "7px 10px", border: `1px solid ${t.accent}`, borderRadius: 5, color: t.accent, fontSize: 14 }}>{fixture.focusLabel}</span></div><div style={{ marginTop: 20 }}><ScreenContent fixture={fixture} /></div><div style={{ marginTop: 18, padding: 14, borderLeft: `3px solid ${t.accent}`, background: "rgba(85,183,246,0.09)" }}><div style={{ color: t.accent, fontWeight: 760, fontSize: 14 }}>FOCUS / {fixture.focusLabel}</div><div style={{ marginTop: 5, color: t.text, fontSize: 17 }}>{fixture.focusDetail}</div></div></main></Panel><Panel style={{ marginTop: 24, minHeight: 150, padding: 18, display: "grid", gridTemplateColumns: "150px minmax(0, 1fr)", gap: 18 }}><div style={{ color: t.warning, fontSize: 14, fontWeight: 780 }}>Caption safe</div><div style={{ fontSize: 20, lineHeight: 1.3, fontWeight: 620 }}>{fixture.caption}</div></Panel></div></AbsoluteFill>;
};
