import { createStyleCoreTokens } from "../../core";

export const cinematicTypeTokens = createStyleCoreTokens({
  meta: {
    familyId: "cinematic-type",
    version: "1.0.0",
  },
  color: {
    canvas: "#151312",
    canvasRaised: "#1F1B19",
    surface: "#26211E",
    surfaceElevated: "#312A26",
    surfaceOverlay: "rgba(18, 15, 14, 0.82)",
    textStrong: "#F5F1EA",
    textMuted: "#C5BBAF",
    textSoft: "#8E837A",
    accent: "#C97C5D",
    accentSoft: "rgba(201, 124, 93, 0.18)",
    success: "#76B89A",
    warning: "#C4A26C",
    danger: "#C86A5C",
    rule: "rgba(245, 241, 234, 0.1)",
    shadow: "rgba(0, 0, 0, 0.36)",
    placeholder: "#6E7379",
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 18,
    lg: 26,
    xl: 42,
    gutter: 24,
    safeMargin: 72,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 18,
    xl: 24,
    pill: 999,
  },
  grid: {
    columns: 12,
    gutter: 24,
    rowGap: 24,
    outerMargin: 72,
    maxContentWidth: 936,
  },
  motion: {
    policy: "full",
    fastFrames: 10,
    normalFrames: 18,
    slowFrames: 28,
    distanceSm: 10,
    distanceMd: 18,
    distanceLg: 26,
  },
  surface: {
    borderWidth: 1,
    shadowBase: "0 20px 42px rgba(0, 0, 0, 0.18)",
    shadowRaised: "0 28px 58px rgba(0, 0, 0, 0.24)",
    shadowOverlay: "0 32px 68px rgba(0, 0, 0, 0.28)",
    highlight: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  media: {
    cornerRadius: 24,
    frameInset: 16,
    placeholderGrid: 34,
    placeholderLabel: "Photographic field pending",
  },
  typography: {
    display: {
      fontFamily: '"Segoe UI", Arial, sans-serif',
      fontSize: 124,
      lineHeight: 0.95,
      fontWeight: 900,
      letterSpacing: 0,
    },
    headline: {
      fontFamily: '"Segoe UI", Arial, sans-serif',
      fontSize: 82,
      lineHeight: 1.02,
      fontWeight: 880,
      letterSpacing: 0,
    },
    title: {
      fontFamily: '"Segoe UI", Arial, sans-serif',
      fontSize: 40,
      lineHeight: 1.1,
      fontWeight: 760,
      letterSpacing: 0,
    },
    body: {
      fontFamily: '"Segoe UI", Arial, sans-serif',
      fontSize: 28,
      lineHeight: 1.3,
      fontWeight: 560,
      letterSpacing: 0,
    },
    label: {
      fontFamily: '"Segoe UI", Arial, sans-serif',
      fontSize: 18,
      lineHeight: 1.16,
      fontWeight: 760,
      letterSpacing: 0,
      textTransform: "uppercase",
    },
    caption: {
      fontFamily: '"Segoe UI", Arial, sans-serif',
      fontSize: 16,
      lineHeight: 1.24,
      fontWeight: 620,
      letterSpacing: 0,
    },
    mono: {
      fontFamily: 'Consolas, "Courier New", monospace',
      fontSize: 18,
      lineHeight: 1.3,
      fontWeight: 600,
      letterSpacing: 0,
    },
  },
});
