// UI copy for the vgov (version governance) pages. Owned by one migration batch
// to keep parallel work conflict-free. Existing vgov.* keys living in common.ts
// (load*/save*/approve*/compare failures) are intentionally not redefined here.
export const vgov = {
  // VgovReleasesPage
  'vgov.deliveryEyebrow': 'Workflow delivery', 'vgov.releasePointers': 'Release pointers', 'vgov.releaseSubtitle': 'Publish then explicitly promote a workflow release. Technical manifest details stay with each output.', 'vgov.workflowIdLabel': 'Workflow ID', 'vgov.refresh': 'Refresh', 'vgov.pointer': '{env} pointer', 'vgov.notPromoted': 'Not promoted', 'vgov.releaseHeader': 'Release', 'vgov.statusHeader': 'Status', 'vgov.actionsHeader': 'Actions', 'vgov.publish': 'Publish', 'vgov.promoteDev': 'Promote DEV', 'vgov.promoteProd': 'Promote / rollback PROD', 'vgov.publishConfirm': 'Publish v{version}?', 'vgov.promoteConfirm': 'Promote v{version} to {env}?', 'vgov.prodConfirmWarn': 'This will move the {env} pointer to v{version}. Production may change immediately.', 'vgov.prodTypePrompt': 'Type PROD to confirm', 'vgov.confirm': 'Confirm', 'vgov.promotedTo': '{version} now points to {env}',
  // VgovRunPage
  'vgov.runEyebrow': 'Project → workflow → run', 'vgov.runWorkflowTitle': 'Run workflow', 'vgov.runSubtitle': 'Choose imported RD, target environment, then name business output.', 'vgov.releaseLive': 'Release live in {env}', 'vgov.commitNotPinned': 'Commit not pinned', 'vgov.noReleaseForEnv': '{env} has no release pointer. Promote a published release before running.', 'vgov.manageReleases': 'Manage releases', 'vgov.projectFieldLabel': 'Project', 'vgov.workflowFieldLabel': 'Workflow', 'vgov.rdInputFieldLabel': 'RD input', 'vgov.environmentFieldLabel': 'Environment', 'vgov.outputBusinessKeyLabel': 'Output business key', 'vgov.runButton': 'Run', 'vgov.runId': 'Run {id}', 'vgov.inputOption': '{key} revision {no}',
  // VgovOutputPage
  'vgov.outputEyebrow': 'Run → output → approve', 'vgov.outputHistoryTitle': 'Output history', 'vgov.projectIdLabel': 'Project ID', 'vgov.preview': 'Preview', 'vgov.editContent': 'Edit content', 'vgov.approve': 'Approve', 'vgov.revisionMarkdownLabel': 'Revision markdown', 'vgov.saveHumanEdit': 'Save human edit', 'vgov.revisionOption': 'Revision {no} · {origin}', 'vgov.emptyArtifactsTitle': 'No outputs yet', 'vgov.emptyArtifactsDesc': 'Pick a project to load its outputs.', 'vgov.emptyRevisionsTitle': 'No revisions yet', 'vgov.emptyRevisionsDesc': 'Pick an artifact to load its revisions.',
  // VgovProvenancePage
  'vgov.provenanceEyebrow': 'Output provenance', 'vgov.provenanceTitle': 'Why this output exists', 'vgov.provenanceSubtitle': 'Follow upstream chain from revision to input. Release and manifest remain collapsed technical details.', 'vgov.outputRevisionPlaceholder': 'Output revision UUID', 'vgov.revisionUuidLabel': 'Revision UUID', 'vgov.trace': 'Trace', 'vgov.node.output': 'Output revision', 'vgov.node.parent': 'Parent revision', 'vgov.node.run': 'Run', 'vgov.node.noRun': 'No generating run', 'vgov.node.rdInput': 'RD input', 'vgov.unavailable': 'Unavailable', 'vgov.hideTechnical': 'Hide technical details', 'vgov.showTechnical': 'Show release & manifest', 'vgov.workflowPrefix': 'Workflow', 'vgov.manifestPrefix': 'Manifest', 'vgov.gitPrefix': 'Git', 'vgov.emptyProvenanceTitle': 'No provenance yet', 'vgov.emptyProvenanceDesc': 'Trace a revision UUID to surface its chain.',
  // VgovComparePage
  'vgov.compareEyebrow': 'Output → history / compare', 'vgov.compareTitle': 'Explain difference', 'vgov.compareSubtitle': 'Compare two output revisions across all seven provenance categories.', 'vgov.leftPlaceholder': 'Left revision UUID', 'vgov.rightPlaceholder': 'Right revision UUID', 'vgov.leftUuidLabel': 'Left revision UUID', 'vgov.rightUuidLabel': 'Right revision UUID', 'vgov.compareButton': 'Compare', 'vgov.changed': 'Changed', 'vgov.unchanged': 'Unchanged', 'vgov.categoryHeader': 'Category', 'vgov.fromHeader': 'From', 'vgov.valueHeader': 'Value', 'vgov.toHeader': 'To', 'vgov.facetHeader': 'Facet', 'vgov.emptyDiffTitle': 'No comparison yet', 'vgov.emptyDiffDesc': 'Enter two revision UUIDs to see what changed.',
} as const
