// UI copy for the workflows area. Owned by one migration batch to keep parallel work conflict-free.
export const workflows = {
  'workflows.loadFailed': 'Unable to load data', 'workflows.validateSuccess': 'Validation succeeded.', 'workflows.validationBackendError': 'Workflow is invalid — errors below are from the backend.', 'workflows.saved': 'Workflow saved.', 'workflows.saveFailed': 'Unable to save workflow', 'workflows.runFailed': 'Run failed', 'workflows.resolvePendingGate': 'Resolve the pending gate before starting another workflow.', 'workflows.enterObjective': 'Enter an objective before running.', 'workflows.cannotRunInvalid': 'Workflow is invalid — cannot run.', 'workflows.stopping': 'Stopping workflow.', 'workflows.cannotResumeRun': 'Unable to resume run', 'workflows.newWorkflowPrompt': 'Workflow id', 'workflows.newIdPlaceholder': 'lowercase-with-hyphens', 'workflows.create': 'Create', 'workflows.createFailed': 'Unable to create workflow', 'workflows.alreadyExists': 'A workflow with this id already exists', 'workflows.deleteWorkflow': 'Delete workflow', 'workflows.deleteConfirm': 'Delete workflow "{id}"?', 'workflows.deleteFailed': 'Unable to delete workflow', 'workflows.deleted': 'Workflow deleted.', 'workflows.noValidWorkflow': 'No valid workflows.',
  'workflows.orchestration': 'ORCHESTRATION', 'workflows.providers': 'Providers: {providers}', 'workflows.running': 'Running', 'workflows.stop': 'Stop', 'workflows.objectivePlaceholder': 'Run objective…', 'workflows.stoppingLabel': 'Stopping', 'workflows.run': 'Run', 'workflows.checkWorkflow': 'Check workflow', 'workflows.hideInspector': 'Hide inspector', 'workflows.workflowActions': 'Workflow actions', 'workflows.valid': 'Valid', 'workflows.notChecked': 'Not checked', 'workflows.invalidStatus': 'Invalid', 'workflows.invalid': 'Workflow is invalid.', 'workflows.linearOnly': 'The canvas supports only linear chains; current edges have branches, loops, or disconnected nodes.', 'workflows.nodeCount': '{count} nodes', 'workflows.connectionCount': '{count} connections', 'workflows.unsaved': 'Unsaved', 'workflows.savedStatus': 'Saved', 'workflows.zoomIn': 'Zoom in', 'workflows.zoomOut': 'Zoom out', 'workflows.fitCanvas': 'Fit canvas', 'workflows.deleteEdge': 'Delete edge',
  'workflows.new': 'New', 'workflows.searchPlaceholder': 'Search workflows…', 'workflows.edgeCount': '{count} edges', 'workflows.palette': 'Palette', 'workflows.agent': 'Agent', 'workflows.agentField': 'Agent', 'workflows.executionPolicy': 'Execution policy', 'workflows.requiresApproval': 'Requires approval', 'workflows.edgeAria': 'Edge from {from} to {to}', 'workflows.nodeAria': 'Node {id}', 'workflows.connectFrom': 'Connect from {id}', 'workflows.connectTo': 'Connect to {id}', 'workflows.noTarget': 'no target selected', 'workflows.complete': 'Complete', 'workflows.failed': 'Failed',
  'workflows.runInputs': 'Run inputs', 'workflows.artifacts': 'Artifacts', 'workflows.files': 'Files', 'workflows.searchInputs': 'Search inputs…', 'workflows.noArtifacts': 'No artifacts available.', 'workflows.noFiles': 'No files available.', 'workflows.inputArtifact': 'artifact', 'workflows.inputFile': 'file', 'workflows.removeInput': 'Remove input',
  'workflows.runLog': 'Run log', 'workflows.noRun': 'No run yet', 'workflows.sseLogEmpty': 'Logs receive real SSE events when the workflow runs.', 'workflows.edgeInspector': 'Edge inspector', 'workflows.kind': 'Kind', 'workflows.none': 'None', 'workflows.label': 'Label', 'workflows.optionalDisplayLabel': 'Optional display label', 'workflows.selectNodeOrEdge': 'Select a node or edge to open Inspector.', 'workflows.inspector': 'Inspector', 'workflows.overview': 'Overview', 'workflows.contracts': 'Contracts', 'workflows.alerts': 'Alerts', 'workflows.runObjective': 'run objective', 'workflows.outputNode': 'output node {id}', 'workflows.claimsNode': 'claims node {id}', 'workflows.noTokens': 'No tokens.', 'workflows.noRealRuns': 'No real runs yet.', 'workflows.errorEvent': 'Error event', 'workflows.noRealAlerts': 'No real alerts.', 'workflows.selectPriorNode': 'Select a preceding node', 'workflows.invalidJson': 'Invalid JSON', 'workflows.invalidReference': 'Invalid reference: {errors}',
  'workflows.searchAgents': 'Search agents', 'workflows.paletteAgents': 'Agents', 'workflows.paletteNodes': 'Nodes', 'workflows.noAgentsMatch': 'No agents match this search.', 'workflows.addAgentAria': 'Add agent {id}', 'workflows.nodeAppended': 'Added {id} after {after}.', 'workflows.nodeInserted': 'Inserted {id} between {from} and {to}.', 'workflows.validateNode': 'validate',
  'workflows.chooseFolder': 'Choose folder', 'workflows.folderPath': 'Enter a folder path', 'workflows.folderUp': 'Up one level', 'workflows.selectFolder': 'Choose this folder', 'workflows.cancelFolder': 'Cancel', 'workflows.folderAsContext': 'Load files in this folder as context', 'workflows.folderAsScope': 'Allow agent to read this folder', 'workflows.folderWritable': 'Allow agent to write to this folder', 'workflows.folderWritableWarning': 'The agent can write files to this folder.', 'workflows.noFolders': 'No folders available.', 'workflows.folderOutsideWorkspace': 'Outside the Hub workspace: {path}. Agents in this run reach files the workspace boundary normally keeps out.',
} as const
