import { useEffect, useMemo, useState } from 'react'
import { api } from '../lib/api'
import { artifactSummary } from '../lib/artifact'
import { Button, Chip, Input } from '../lib/ui'
import { Markdown } from '../lib/markdown'

type Version = { version: string; created_at: string; content?: string }
type Artifact = { id: string; title: string; created_at: string; source: 'chat' | 'workflow_run'; version?: string; versions: Version[] }
type CachedChat = { id: string; title: string; messages?: { role: string; content: string; streaming?: boolean }[] }
const cacheKey = 'hub-v3-chats'
const artifactCacheKey = 'hub-v3-artifacts'
const fallback = (): Artifact[] => { try { const cached = JSON.parse(localStorage.getItem(artifactCacheKey) ?? 'null'); if (Array.isArray(cached)) return cached as Artifact[]; const chats = JSON.parse(localStorage.getItem(cacheKey) ?? '[]') as CachedChat[]; return chats.flatMap(chat => (chat.messages ?? []).filter(message => message.role === 'assistant' && !message.streaming && message.content.length >= 1200).map((message, index) => ({ id: `${chat.id}:${index}`, title: artifactSummary(message.content).title, created_at: '', source: 'chat' as const, version: 'v1', versions: [{ version: 'v1', created_at: '', content: message.content }] }))) } catch { return [] } }
const fmt = (value?: string) => value ? new Date(value).toLocaleString('vi-VN') : '—'

export default function ArtifactsPage() {
  const [items, setItems] = useState<Artifact[]>(fallback); const [online, setOnline] = useState(false); const [query, setQuery] = useState(''); const [selectedId, setSelectedId] = useState(items[0]?.id ?? ''); const [tab, setTab] = useState<'Output' | 'Review Issues' | 'References' | 'Versions'>('Output')
  useEffect(() => { void api<{ artifacts: Artifact[] }>('/api/artifacts').then(data => { localStorage.setItem(artifactCacheKey, JSON.stringify(data.artifacts)); setItems(data.artifacts); setOnline(true); setSelectedId(current => current || data.artifacts[0]?.id || '') }).catch(() => setOnline(false)) }, [])
  const filtered = useMemo(() => items.filter(item => item.title.toLowerCase().includes(query.toLowerCase())), [items, query])
  const selected = items.find(item => item.id === selectedId) ?? filtered[0]
  const [detail, setDetail] = useState<Artifact | null>(null)
  useEffect(() => { if (!selected || !online) { setDetail(selected ?? null); return } void api<Artifact>(`/api/artifacts/${encodeURIComponent(selected.id)}`).then(setDetail).catch(() => setDetail(selected)) }, [selected?.id, online])
  const shown = detail?.id === selected?.id ? detail : selected
  const latest = shown?.versions.at(-1)
  const empty = <div className="rounded-lg border border-dashed border-border-subtle px-space-4 py-space-8 text-center"><div className="text-label font-semibold text-primary">Chưa có dữ liệu</div><p className="mt-space-1 text-caption text-muted">Không có dữ liệu cho mục này.</p></div>
  return <div className="flex h-full min-h-0 flex-col gap-space-4 p-space-6">
    <div className="flex flex-wrap items-end justify-between gap-space-3"><div><div className="mb-space-1 text-section font-semibold uppercase tracking-section text-muted">ĐIỀU PHỐI</div><h1 className="text-title font-semibold text-primary">Artifacts</h1><p className="mt-space-1 text-caption text-secondary">Artifact lưu trên máy chủ. {online ? 'Đang đồng bộ.' : 'Đang dùng cache cục bộ.'}</p></div><Button variant="secondary" onClick={() => { window.location.hash = '#/chat' }} disabled={!selected}>Edit in Chat</Button></div>
    <div className="flex min-h-0 flex-1 gap-space-4 overflow-hidden">
      <aside className="flex w-[280px] shrink-0 flex-col overflow-hidden rounded-lg border border-border-subtle bg-surface"><div className="border-b border-border-subtle p-space-3"><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm artifact…" aria-label="Tìm artifact" /></div><div className="min-h-0 flex-1 overflow-y-auto p-space-2">{filtered.length === 0 ? <p className="p-space-3 text-caption text-muted">Chưa có artifact nào.</p> : filtered.map(item => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`mb-space-1 block w-full rounded-md p-space-3 text-left ${item.id === selected?.id ? 'bg-accent-subtle' : 'hover:bg-hover'}`}><div className="flex items-center gap-space-2"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-elevated text-accent">▤</span><span className="min-w-0 flex-1 truncate text-label font-semibold text-primary">{item.title}</span></div><div className="mt-space-2 text-caption text-muted">{item.source === 'chat' ? 'Chat' : 'Workflow run'} · {item.version ?? '—'}</div></button>)}</div></aside>
      <main className="flex min-w-0 flex-1 flex-col overflow-hidden rounded-lg border border-border-subtle bg-surface"><div className="flex flex-wrap items-center gap-space-2 border-b border-border-subtle p-space-3">{(['Output', 'Review Issues', 'References', 'Versions'] as const).map(name => <button key={name} onClick={() => setTab(name)} className={`rounded-md px-space-3 py-space-2 text-label ${tab === name ? 'bg-accent-subtle font-semibold text-primary' : 'text-secondary hover:bg-hover'}`}>{name}{name === 'Versions' ? ` (${shown?.versions.length ?? 0})` : ''}</button>)}</div>{shown ? <><div className="border-b border-border-subtle p-space-5"><div className="flex items-start justify-between gap-space-4"><div><h2 className="text-title font-semibold text-primary">{shown.title}</h2><div className="mt-space-2 text-caption text-secondary">{shown.source === 'chat' ? 'Chat' : 'Workflow run'}</div></div><Chip>{latest?.version ?? '—'} · hiện tại</Chip></div><div className="mt-space-4 grid grid-cols-2 gap-space-3 text-caption md:grid-cols-3">{[['Workflow name', '—'], ['Run ID', '—'], ['Được tạo bởi', shown.source === 'chat' ? 'Chat' : 'Workflow run'], ['Bắt đầu lúc', fmt(shown.created_at)], ['Hoàn thành lúc', fmt(latest?.created_at)], ['Thời gian chạy', '—']].map(([label, value]) => <div key={label}><div className="text-muted">{label}</div><div className="mt-1 text-secondary">{value}</div></div>)}</div></div><div className="min-h-0 flex-1 overflow-y-auto p-space-5">{tab === 'Output' ? latest?.content ? <div className="artifact-panel text-label"><Markdown source={latest.content} /></div> : empty : tab === 'Versions' ? <div className="space-y-space-2">{shown.versions.slice().reverse().map(version => <div key={version.version} className="rounded-md border border-border-subtle p-space-3 text-label"><b>{version.version}</b><div className="mt-1 text-caption text-muted">{fmt(version.created_at)}</div></div>)}</div> : empty}</div></> : <div className="flex flex-1 items-center justify-center p-space-6 text-label text-muted">Chưa có artifact nào.</div>}</main>
    </div>
  </div>
}
