import { useEffect, useMemo, useRef, useState } from 'react'
import { api, apiRequest } from '../lib/api'
import { parseSse } from '../lib/sse'
import { Markdown } from '../lib/markdown'

type Provider = { id: string; available: boolean; detail: string }
type Catalog = { id: string; shortName?: string; category?: string; label?: string }
type Message = { role: 'user' | 'assistant' | 'system'; content: string; reasoning?: string; thinkingOpen?: boolean; usage?: Record<string, unknown>; streaming?: boolean }
type Pane = { id: string; provider: string; model: string; title: string; messages: Message[]; cliSessionId?: string }
const colors: Record<string, string> = { claude: 'bg-claude', codex: 'bg-codex', nvidia: 'bg-nvidia', gemini: 'bg-gemini' }
const ro = (provider: string) => provider !== 'nvidia'
const makePane = (provider = 'nvidia', model = ''): Pane => ({ id: crypto.randomUUID(), provider, model, title: provider, messages: [] })

export default function ChatPage() {
  const [panes, setPanes] = useState<Pane[]>(() => { try { return JSON.parse(localStorage.getItem('hub-v3-chat') ?? 'null') ?? [makePane()] } catch { return [makePane()] } })
  const [providers, setProviders] = useState<Provider[]>([]); const [catalog, setCatalog] = useState<Catalog[]>([]); const [defaultModel, setDefaultModel] = useState(''); const [broadcast, setBroadcast] = useState(false); const [shared, setShared] = useState('')
  useEffect(() => { localStorage.setItem('hub-v3-chat', JSON.stringify(panes.map(p => ({ ...p, messages: p.messages.map(({ streaming, ...m }) => m) })))) }, [panes])
  useEffect(() => { void Promise.all([api<Provider[]>('/api/providers'), api<{ catalog: Catalog[]; default: string }>('/api/chat/models')]).then(([p, m]) => { setProviders(p); setCatalog(m.catalog); setDefaultModel(m.default); setPanes(current => current.map(pane => pane.provider === 'nvidia' && !pane.model ? { ...pane, model: m.default } : pane)) }).catch(() => undefined) }, [])
  const add = (provider: string) => { if (panes.length < 4) setPanes(current => [...current, makePane(provider, provider === 'nvidia' ? defaultModel : '')]) }
  const update = (id: string, change: Partial<Pane>) => setPanes(current => current.map(p => p.id === id ? { ...p, ...change } : p))
  const sendAll = (text: string) => { if (!text.trim()) return; if (broadcast) { setShared(''); panes.forEach(p => { if (!p.messages.at(-1)?.streaming) void send(p.id, text) }) } }
  const send = async (id: string, text: string) => {
    const pane = panes.find(p => p.id === id); if (!pane || !text.trim()) return
    const user: Message = { role: 'user', content: text }; const assistant: Message = { role: 'assistant', content: '', reasoning: '', streaming: true }
    const history = [...pane.messages, user]; update(id, { messages: [...history, assistant] })
    const controller = new AbortController(); controllers.current.set(id, controller)
    // NVIDIA receives full history; CLI providers resume with only the new user message when a session exists.
    const messages = pane.provider !== 'nvidia' && pane.cliSessionId ? [user] : history
    try {
      const response = await apiRequest('/api/chat', { method: 'POST', body: JSON.stringify({ provider: pane.provider, model: pane.model || undefined, messages, session_id: pane.cliSessionId }), signal: controller.signal })
      if (!response.body) throw new Error('Chat stream unavailable')
      for await (const item of parseSse(response.body)) {
        const data = item.data as Record<string, unknown>
        if (item.event === 'reasoning') patchMessage(id, current => ({ reasoning: `${current.reasoning ?? ''}${String(data.text ?? '')}`, streaming: true }))
        if (item.event === 'delta') patchMessage(id, current => ({ content: `${current.content}${String(data.text ?? '')}`, streaming: true }))
        if (item.event === 'done') { patchMessage(id, { streaming: false, usage: data.usage as Record<string, unknown> }); update(id, { cliSessionId: typeof data.session_id === 'string' ? data.session_id : pane.cliSessionId, model: typeof data.model === 'string' && pane.provider === 'nvidia' ? data.model : pane.model }) }
        if (item.event === 'error') patchMessage(id, { role: 'system', content: String(data.message ?? 'Chat stream error'), streaming: false })
      }
    } catch (error) { if ((error as Error).name !== 'AbortError') patchMessage(id, { role: 'system', content: (error as Error).message, streaming: false }) }
    finally { patchMessage(id, { streaming: false }); controllers.current.delete(id) }
  }
  const controllers = useRef(new Map<string, AbortController>())
  const patchMessage = (id: string, change: Partial<Message> | ((m: Message) => Partial<Message>)) => setPanes(current => current.map(p => p.id === id ? { ...p, messages: p.messages.map((m, n) => n === p.messages.length - 1 ? { ...m, ...(typeof change === 'function' ? change(m) : change) } : m) } : p))
  return <div className="flex h-full min-h-0 flex-col gap-3 p-4"><div className="flex flex-wrap items-center gap-2"><select aria-label="Provider cho cửa sổ mới" defaultValue="nvidia" className="rounded-lg border border-line bg-panel2 px-2 py-2 text-xs text-text" id="new-pane-provider">{providers.map(p => <option key={p.id} value={p.id} disabled={!p.available}>{p.id}{p.available ? '' : ` — ${p.detail}`}</option>)}</select><button onClick={() => add((document.getElementById('new-pane-provider') as HTMLSelectElement)?.value ?? 'nvidia')} disabled={panes.length >= 4} className="rounded-lg border border-line bg-panel2 px-3 py-2 text-xs font-semibold disabled:opacity-40">+ Cửa sổ</button><label className="flex items-center gap-2 text-xs text-dim"><input type="checkbox" checked={broadcast} onChange={e => setBroadcast(e.target.checked)} />Gửi tất cả</label>{broadcast && <div className="flex min-w-[240px] flex-1 gap-2"><input value={shared} onChange={e => setShared(e.target.value)} onKeyDown={e => e.key === 'Enter' && sendAll(shared)} placeholder="Nhắn mọi cửa sổ…" className="min-w-0 flex-1 rounded-lg border border-line bg-panel2 px-3 py-2 text-xs text-text" /><button onClick={() => sendAll(shared)} className="rounded-lg border border-line px-3 text-xs">Gửi</button></div>}{providers.filter(p => !p.available).map(p => <span key={p.id} title={p.detail} className="text-[11px] text-faint">{p.id} không khả dụng</span>)}</div><div className={`chat-grid grid min-h-0 flex-1 gap-px overflow-hidden rounded-lg border border-line bg-line panes-${panes.length}`}>{panes.map(p => <PaneView key={p.id} pane={p} catalog={catalog} onUpdate={change => update(p.id, change)} onClose={() => setPanes(current => current.filter(x => x.id !== p.id))} onSend={text => void send(p.id, text)} onStop={() => controllers.current.get(p.id)?.abort()} onClear={() => update(p.id, { messages: [] })} />)}</div></div>
}

function PaneView({ pane, catalog, onUpdate, onClose, onSend, onStop, onClear }: { pane: Pane; catalog: Catalog[]; onUpdate: (c: Partial<Pane>) => void; onClose: () => void; onSend: (s: string) => void; onStop: () => void; onClear: () => void }) {
  const [text, setText] = useState(''); const grouped = useMemo(() => catalog.reduce<Record<string, Catalog[]>>((all, model) => { const key = model.category ?? 'Models'; (all[key] ??= []).push(model); return all }, {}), [catalog]); const last = pane.messages.at(-1)
  const download = () => { const body = pane.messages.map(m => `## ${m.role}\n\n${m.content}`).join('\n\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([body], { type: 'text/markdown' })); a.download = `${pane.provider}-transcript.md`; a.click(); URL.revokeObjectURL(a.href) }
  const submit = () => { if (last?.streaming) onStop(); else { onSend(text); setText('') } }
  return <article className="pane flex min-h-0 min-w-0 flex-col bg-ink"><header className="flex flex-wrap items-center gap-2 border-b border-line bg-panel px-3 py-2 text-xs"><i className={`h-2 w-2 rounded-full ${colors[pane.provider] ?? 'bg-faint'}`} /><span className="font-mono">{pane.provider} · {pane.model ? (catalog.find(x => x.id === pane.model)?.shortName ?? pane.model.split('/').at(-1)) : 'mặc định'}</span>{pane.cliSessionId && <span className="font-mono text-[10px] text-faint">…{pane.cliSessionId.slice(-8)}</span>}<span className="ml-auto rounded-full border border-line px-2 py-px font-mono text-[10px] text-faint">{ro(pane.provider) ? 'READ-ONLY' : 'FREE'}</span><button onClick={download} title="Xuất .md" className="text-dim">Xuất .md</button><button onClick={onClear} title="Xoá" className="text-dim">Xoá</button><button onClick={onClose} className="text-dim">×</button></header><div className="border-b border-line bg-panel px-3 py-2">{pane.provider === 'nvidia' ? <select value={pane.model || catalog[0]?.id || ''} onChange={e => onUpdate({ model: e.target.value })} className="w-full rounded border border-line bg-panel2 px-2 py-1 text-xs text-text">{Object.entries(grouped).map(([category, models]) => <optgroup key={category} label={category}>{(models as Catalog[]).map(m => <option key={m.id} value={m.id}>{m.shortName ?? m.label ?? m.id}</option>)}</optgroup>)}</select> : <input value={pane.model} onChange={e => onUpdate({ model: e.target.value })} placeholder="mặc định" className="w-full rounded border border-line bg-panel2 px-2 py-1 text-xs text-text" />}</div><div className="msgs flex-1 space-y-2 overflow-y-auto p-3">{pane.messages.map((m, i) => <MessageView key={i} message={m} />)}</div><form onSubmit={e => { e.preventDefault(); submit() }} className="flex gap-2 border-t border-line p-3"><input value={text} onChange={e => setText(e.target.value)} placeholder={`Nhắn ${pane.provider}…`} className="min-w-0 flex-1 rounded-lg border border-line bg-panel2 px-3 py-2 text-xs text-text" /><button className="rounded-lg border border-line bg-panel2 px-3 text-xs">{last?.streaming ? 'Dừng' : 'Gửi'}</button></form></article>
}

function MessageView({ message }: { message: Message }) { const [open, setOpen] = useState(false); const copy = () => void navigator.clipboard?.writeText(message.content); const usage = message.usage ? Object.entries(message.usage).filter(([, v]) => v != null).map(([k, v]) => `${k}: ${String(v)}`).join(' · ') : ''; return <div className={`message max-w-[90%] rounded-lg border border-line px-3 py-2 text-xs ${message.role === 'user' ? 'ml-auto bg-panel2' : message.role === 'system' ? 'border-err text-err' : 'bg-panel text-dim'}`}><div className="whitespace-pre-wrap">{message.role === 'assistant' && !message.streaming ? <Markdown source={message.content} /> : message.content}</div>{message.reasoning && <><button onClick={() => setOpen(!open)} className="mt-2 text-[10px] text-faint">{open ? 'Ẩn suy nghĩ' : 'Hiện suy nghĩ'}</button>{open && <div className="mt-1 whitespace-pre-wrap border-l border-line pl-2 font-mono text-[10px] text-faint">{message.reasoning}</div>}</>}{usage && <div className="mt-2 font-mono text-[10px] text-faint">{usage}</div>}{message.content && <button onClick={copy} className="mt-2 block text-[10px] text-faint">Copy</button>}</div> }
