import { useEffect, useMemo, useState } from 'react'
import { ApiError, api } from '../lib/api'
import { Markdown } from '../lib/markdown'
import Table from '../lib/Table'

type Skill = { id: string; name: string; description: string; source: string; path: string; content_hash: string; coverage: string[]; last_used: string | null; use_count_30d: number | null }
type Detail = Skill & { content: string; files: string[] }; type Drift = { name: string; variants: { id: string; source: string; path: string; content_hash: string; mtime: string | null }[]; in_sync: boolean }; type Log = Record<string, unknown>
export default function SkillsPage() {
  const [skills, setSkills] = useState<Skill[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [drift, setDrift] = useState<Drift[]>([]); const [log, setLog] = useState<Log[]>([]); const [target, setTarget] = useState(''); const [error, setError] = useState(''); const targets = useMemo(() => [...new Set(skills.map(skill => skill.source))], [skills])
  const load = () => { setError(''); void Promise.all([api<Skill[]>('/api/skill-library'), api<Drift[]>('/api/skill-library/drift'), api<Log[]>('/api/skill-library/deploy-log')]).then(([s, d, l]) => { setSkills(s); setDrift(d); setLog(l); setTarget(current => current || s[0]?.source || '') }).catch(e => setError(e instanceof ApiError ? e.message : 'KhÃ´ng thá»ƒ táº£i skill library')) }
  useEffect(load, [])
  const choose = (skill: Skill) => { setError(''); void api<Detail>(`/api/skill-library/${skill.id}`).then(setDetail).catch(e => setError(e instanceof ApiError ? e.message : 'KhÃ´ng thá»ƒ táº£i skill')) }
  const deploy = async (skill: Skill) => { if (!target) return; try { await api(`/api/skill-library/${encodeURIComponent(skill.id)}/deploy`, { method: 'POST', body: JSON.stringify({ target }) }); setLog(await api<Log[]>('/api/skill-library/deploy-log')); setError('') } catch (e) { setError(e instanceof ApiError ? e.message : 'Triá»ƒn khai tháº¥t báº¡i') } }
  return <div className="flex h-full min-h-0 flex-col gap-4 p-7"><div><div className="mb-2 text-[length:var(--hub-section-size)] font-semibold uppercase tracking-[var(--hub-section-tracking)] text-faint">ÄIá»€U PHá»I</div><h1 className="text-[length:var(--hub-title-size)] font-semibold">Skills</h1></div>{error && <div className="text-xs text-err">{error}</div>}<section className="min-h-0 overflow-auto"><Table headers={['Name', 'Source', 'Description', 'Telemetry', 'Deploy']}>{skills.map(skill => <tr key={skill.id} onClick={() => choose(skill)} className="cursor-pointer hover:bg-panel2"><td className="px-3 py-2 font-mono text-text">{skill.name}</td><td className="px-3 py-2 text-dim">{skill.source}</td><td className="max-w-sm px-3 py-2 text-dim">{skill.description || 'â€”'}</td><td className="px-3 py-2 font-mono text-[10px] text-faint">{skill.use_count_30d ?? 'â€”'} / {skill.last_used ?? 'â€”'}</td><td className="px-3 py-2"><button onClick={e => { e.stopPropagation(); void deploy(skill) }} className="rounded border border-line px-2 py-1 text-[10px]">Triá»ƒn khai</button></td></tr>)}</Table></section><div className="flex flex-wrap items-center gap-2 text-xs"><span>ÄÃ­ch triá»ƒn khai</span><select value={target} onChange={e => setTarget(e.target.value)} className="rounded border border-line bg-panel2 px-2 py-1">{targets.map(value => <option key={value}>{value}</option>)}</select></div>{detail && <section className="min-h-0 overflow-auto rounded-lg border border-line bg-panel p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-mono text-sm">{detail.name}</h2><div className="text-[10px] text-faint">{detail.id} Â· {detail.source} Â· {detail.content_hash}</div></div><button onClick={() => setDetail(null)} className="text-dim">Ã—</button></div><Markdown source={detail.content} /></section>}<section className="rounded-lg border border-line bg-panel p-4"><h2 className="mb-2 text-xs font-semibold">Drift</h2>{drift.filter(row => !row.in_sync).length ? drift.filter(row => !row.in_sync).map(row => <div key={row.name} className="mb-2 text-xs text-gate"><span className="font-mono">{row.name}</span> Â· {row.variants.length} variants</div>) : <div className="text-xs text-faint">KhÃ´ng cÃ³ drift</div>}<details className="mt-3 text-xs"><summary className="cursor-pointer text-dim">Deploy log ({log.length})</summary>{log.map((row, index) => <pre key={index} className="mt-1 whitespace-pre-wrap font-mono text-[10px] text-faint">{JSON.stringify(row)}</pre>)}</details></section></div>
}
