import { useEffect, useState } from 'react'
import { ApiError, api } from '../lib/api'
import Table from '../lib/Table'

type Node = { id: string; agent: string; prompt: string; gate?: string | null }
type Workflow = { id: string; nodes: Node[]; edges: unknown[]; stop: unknown }
type Validation = { ok: boolean; errors: string[]; ir: unknown[] | null }

export default function WorkflowsPage() {
  const [items, setItems] = useState<Workflow[]>([]); const [selected, setSelected] = useState<Workflow | null>(null); const [yaml, setYaml] = useState(''); const [validation, setValidation] = useState<Validation | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => { void api<Workflow[]>('/api/workflows').then(rows => { setItems(rows); setSelected(current => current ?? rows[0] ?? null) }).catch(e => setError(e instanceof ApiError ? e.message : 'Không thể tải workflow')) }
  useEffect(load, [])
  useEffect(() => { if (!selected) return; setYaml(''); setValidation(null); void api<Validation>('/api/workflows/validate', { method: 'POST', body: JSON.stringify({ id: selected.id }) }).then(setValidation).catch(e => setError(e instanceof ApiError ? e.message : 'Không thể đọc workflow')) }, [selected])
  const validate = async () => { setError(''); if (!yaml.trim()) return setValidation({ ok: false, errors: ['Hãy dán YAML workflow để kiểm tra.'], ir: null }); try { setValidation(await api<Validation>('/api/workflows/validate', { method: 'POST', body: JSON.stringify({ yaml_text: yaml }) })) } catch (e) { setError(e instanceof ApiError ? e.message : 'Validate thất bại') } }
  const save = async () => { if (!selected || !yaml.trim()) return; setSaving(true); setError(''); try { const saved = await api<Workflow>(`/api/workflows/${encodeURIComponent(selected.id)}`, { method: 'PUT', body: JSON.stringify({ yaml_text: yaml }) }); setItems(rows => rows.map(row => row.id === saved.id ? saved : row)); setSelected(saved); setYaml(''); setValidation(null) } catch (e) { setError(e instanceof ApiError ? e.message : 'Không thể lưu workflow') } finally { setSaving(false) } }
  return <div className="flex h-full min-h-0 flex-col gap-4 p-7"><div><div className="mb-2 text-[10px] font-semibold uppercase tracking-[.14em] text-faint">ĐIỀU PHỐI</div><h1 className="text-xl font-semibold">Workflows</h1></div>{error && <div className="text-xs text-err">{error}</div>}<div className="flex min-h-0 flex-1 flex-col gap-3 overflow-hidden lg:flex-row"><aside className="w-full shrink-0 overflow-auto rounded-lg border border-line bg-panel p-2 lg:w-64"><div className="mb-2 px-2 text-[10px] uppercase tracking-wider text-faint">Workflow · {items.length}</div>{items.map(row => <button key={row.id} onClick={() => setSelected(row)} className={`mb-1 w-full rounded border px-3 py-2 text-left ${selected?.id === row.id ? 'border-codex bg-panel2' : 'border-transparent hover:bg-panel2'}`}><div className="font-mono text-xs">{row.id}</div><div className="mt-1 flex gap-2 text-[10px] text-dim"><span>{row.nodes.length} node</span>{row.nodes.some(node => node.gate === 'approval') && <span className="rounded-full border border-gate px-1.5 text-gate">approval</span>}</div></button>)}</aside>{selected && <main className="min-h-0 min-w-0 flex-1 overflow-auto rounded-lg border border-line bg-panel p-4"><div className="flex flex-wrap items-center gap-2"><h2 className="font-mono text-sm">{selected.id}</h2><button onClick={() => { window.location.hash = `/runs?wf=${encodeURIComponent(selected.id)}` }} className="ml-auto rounded bg-codex px-3 py-1.5 text-xs font-semibold text-ink">Chạy</button><button onClick={() => void validate()} className="rounded border border-line px-3 py-1.5 text-xs">Kiểm tra</button><button disabled={!yaml.trim() || saving} onClick={() => void save()} className="rounded border border-line px-3 py-1.5 text-xs disabled:opacity-40">{saving ? 'Đang lưu…' : 'Lưu'}</button></div><section className="mt-4"><h3 className="mb-2 text-xs font-semibold">Các node đã phân tích</h3><Table headers={['ID', 'Agent', 'Gate', 'Prompt']}>{selected.nodes.map(node => <tr key={node.id}><td className="px-3 py-2 font-mono">{node.id}</td><td className="px-3 py-2">{node.agent}</td><td className="px-3 py-2 text-gate">{node.gate ?? '—'}</td><td className="px-3 py-2 text-dim">{node.prompt}</td></tr>)}</Table></section><label className="mt-4 block text-xs font-semibold">YAML workflow<textarea value={yaml} onChange={e => setYaml(e.target.value)} rows={10} placeholder="YAML không có endpoint đọc thô. Dán YAML vào đây để kiểm tra hoặc lưu." className="mt-2 w-full resize-y rounded border border-line bg-panel2 p-3 font-mono text-xs text-text" /></label>{validation && <div className={`mt-3 rounded border p-3 text-xs ${validation.ok ? 'border-ok text-ok' : 'border-err text-err'}`}>{validation.ok ? 'Workflow hợp lệ.' : validation.errors.join('; ')}</div>}</main>}</div></div>
}
